Implement programmatic api
berzniz/now-logs-server pull request #3
Opened 2017-01-10 21:57 UTC by timneutkens

Moved the website to website.js. Website.js should move to a seperate package (with the website folder ofcourse)

2017-01-10 21:58 UTC, timneutkens commented
Also this package (now-logs-server) can be published to npm. Programmatic usage:
`require('now-logs-server/server')(io)`

2017-01-14 13:30 UTC, berzniz requested changes
I think this is a good change overall, but it's a lot of changes. I added my comments inline.

The website should also be split into its own repo and a `now-logs-server` npm package should be published, I will do this later

2017-01-14 13:30 UTC, berzniz commented on index.js
>  if (process.env.NOW_LOGS_SECRET_KEY) {
Can be simplified to:
```
if (NOW_LOGS_SECRET_KEY) {
```

2017-01-14 13:30 UTC, berzniz commented on package.json
> +  "files": [
Can you clarify what this does exactly? Does it only apply to `now.sh` service?

2017-01-14 13:30 UTC, berzniz commented on website.js
> +if (process.env.NOW_LOGS_SECRET_KEY) {
Can be simplified to:
```
if (NOW_LOGS_SECRET_KEY) {
```

2017-01-14 13:30 UTC, berzniz commented on yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
While `yarn` is cool, I'd leave this out and keep only the `npm` version in. This makes it too opintionated

2017-01-15 11:03 UTC, timneutkens commented on package.json
> +  "files": [
It applies to both, so good catch, added `server.js`.

`website.js` and the `website` folder should be moved into a seperate repo 👍

2017-01-22 21:13 UTC, berzniz approved these changes

2017-01-22 21:13 UTC, merged